[2024-05-28 16:24:18,866] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.transform 2024-05-27T02:00:00+00:00 [queued]>
[2024-05-28 16:24:18,878] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.transform 2024-05-27T02:00:00+00:00 [queued]>
[2024-05-28 16:24:18,880] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-28 16:24:18,881] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-28 16:24:18,881] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-28 16:24:18,897] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): transform> on 2024-05-27T02:00:00+00:00
[2024-05-28 16:24:18,903] {standard_task_runner.py:52} INFO - Started process 209 to run task
[2024-05-28 16:24:18,907] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'transform', '2024-05-27T02:00:00+00:00', '--job-id', '512', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmptd_6ws7x', '--error-file', '/tmp/tmpzblal5br']
[2024-05-28 16:24:18,916] {standard_task_runner.py:77} INFO - Job 512: Subtask transform
[2024-05-28 16:24:18,983] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.transform 2024-05-27T02:00:00+00:00 [running]> on host a3c9b0e21f74
[2024-05-28 16:24:19,026] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2024-05-27T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-27T02:00:00+00:00
[2024-05-28 16:24:22,085] {taskinstance.py:1455} ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_init_data.py", line 29, in transform
    transformed_data = response.json()['data']
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-05-28 16:24:22,124] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=load_init_data, task_id=transform, execution_date=20240527T020000, start_date=20240528T162418, end_date=20240528T162422
[2024-05-28 16:24:22,216] {local_task_job.py:146} INFO - Task exited with return code 1
[2024-06-09 14:01:27,961] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.transform 2024-05-27T02:00:00+00:00 [queued]>
[2024-06-09 14:01:28,046] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.transform 2024-05-27T02:00:00+00:00 [queued]>
[2024-06-09 14:01:28,047] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:01:28,048] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-09 14:01:28,055] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:01:28,100] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): transform> on 2024-05-27T02:00:00+00:00
[2024-06-09 14:01:28,128] {standard_task_runner.py:52} INFO - Started process 219 to run task
[2024-06-09 14:01:28,137] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'transform', '2024-05-27T02:00:00+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpqtnoqrnv', '--error-file', '/tmp/tmpgbe9cu1y']
[2024-06-09 14:01:28,153] {standard_task_runner.py:77} INFO - Job 26: Subtask transform
[2024-06-09 14:01:28,289] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.transform 2024-05-27T02:00:00+00:00 [running]> on host 97b873bf6d4d
[2024-06-09 14:01:28,405] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2024-05-27T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-27T02:00:00+00:00
[2024-06-09 14:02:23,778] {python.py:118} INFO - Done. Returned value was: None
[2024-06-09 14:02:23,860] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=transform, execution_date=20240527T020000, start_date=20240609T140127, end_date=20240609T140223
[2024-06-09 14:02:24,041] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-09 14:02:24,169] {local_task_job.py:146} INFO - Task exited with return code 0
