[2024-05-26 22:31:59,806] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-26T22:29:55.687041+00:00 [queued]>
[2024-05-26 22:31:59,816] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-26T22:29:55.687041+00:00 [queued]>
[2024-05-26 22:31:59,816] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 22:31:59,816] {taskinstance.py:1043} INFO - Starting attempt 2 of 6
[2024-05-26 22:31:59,817] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 22:31:59,823] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-05-26T22:29:55.687041+00:00
[2024-05-26 22:31:59,826] {standard_task_runner.py:52} INFO - Started process 187 to run task
[2024-05-26 22:31:59,830] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'save_into_db', '2024-05-26T22:29:55.687041+00:00', '--job-id', '454', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmph3b788_n', '--error-file', '/tmp/tmp086wftbt']
[2024-05-26 22:31:59,832] {standard_task_runner.py:77} INFO - Job 454: Subtask save_into_db
[2024-05-26 22:31:59,864] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.save_into_db 2024-05-26T22:29:55.687041+00:00 [running]> on host 1f334d963743
[2024-05-26 22:31:59,889] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T22:29:55.687041+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-26T22:29:55.687041+00:00
[2024-05-26 22:32:00,091] {python.py:118} INFO - Done. Returned value was: None
[2024-05-26 22:32:00,104] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=save_into_db, execution_date=20240526T222955, start_date=20240526T223159, end_date=20240526T223200
[2024-05-26 22:32:00,123] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26 22:32:00,135] {local_task_job.py:146} INFO - Task exited with return code 0
