[2024-05-26 21:34:09,308] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-26T21:34:05.979008+00:00 [queued]>
[2024-05-26 21:34:09,316] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-26T21:34:05.979008+00:00 [queued]>
[2024-05-26 21:34:09,317] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:34:09,317] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-26 21:34:09,317] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:34:09,327] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-05-26T21:34:05.979008+00:00
[2024-05-26 21:34:09,331] {standard_task_runner.py:52} INFO - Started process 248 to run task
[2024-05-26 21:34:09,334] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'save_into_db', '2024-05-26T21:34:05.979008+00:00', '--job-id', '410', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpto5u47jk', '--error-file', '/tmp/tmp73fq5ov3']
[2024-05-26 21:34:09,337] {standard_task_runner.py:77} INFO - Job 410: Subtask save_into_db
[2024-05-26 21:34:09,364] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.save_into_db 2024-05-26T21:34:05.979008+00:00 [running]> on host 9c777ac19e23
[2024-05-26 21:34:09,390] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T21:34:05.979008+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-26T21:34:05.979008+00:00
[2024-05-26 21:34:09,615] {python.py:118} INFO - Done. Returned value was: None
[2024-05-26 21:34:09,623] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=save_into_db, execution_date=20240526T213405, start_date=20240526T213409, end_date=20240526T213409
[2024-05-26 21:34:09,641] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26 21:34:09,681] {local_task_job.py:146} INFO - Task exited with return code 0
