[2024-05-26 21:55:04,843] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.save_into_db 2024-05-26T21:52:23.478777+00:00 [queued]>
[2024-05-26 21:55:04,854] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.save_into_db 2024-05-26T21:52:23.478777+00:00 [queued]>
[2024-05-26 21:55:04,854] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:55:04,854] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-26 21:55:04,854] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:55:04,860] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-05-26T21:52:23.478777+00:00
[2024-05-26 21:55:04,863] {standard_task_runner.py:52} INFO - Started process 295 to run task
[2024-05-26 21:55:04,866] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_new_data', 'save_into_db', '2024-05-26T21:52:23.478777+00:00', '--job-id', '429', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_new_data.py', '--cfg-path', '/tmp/tmpkqyxx9h6', '--error-file', '/tmp/tmpzrn3_ja1']
[2024-05-26 21:55:04,868] {standard_task_runner.py:77} INFO - Job 429: Subtask save_into_db
[2024-05-26 21:55:04,893] {logging_mixin.py:104} INFO - Running <TaskInstance: get_new_data.save_into_db 2024-05-26T21:52:23.478777+00:00 [running]> on host 9c777ac19e23
[2024-05-26 21:55:04,917] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_new_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T21:52:23.478777+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-26T21:52:23.478777+00:00
[2024-05-26 21:55:04,966] {python.py:118} INFO - Done. Returned value was: None
[2024-05-26 21:55:04,972] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=get_new_data, task_id=save_into_db, execution_date=20240526T215223, start_date=20240526T215504, end_date=20240526T215504
[2024-05-26 21:55:04,990] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26 21:55:05,007] {local_task_job.py:146} INFO - Task exited with return code 0
