[2024-05-26 22:36:42,308] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.save_into_db 2024-05-26T22:33:41.250863+00:00 [queued]>
[2024-05-26 22:36:42,317] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.save_into_db 2024-05-26T22:33:41.250863+00:00 [queued]>
[2024-05-26 22:36:42,318] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 22:36:42,318] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-26 22:36:42,318] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 22:36:42,324] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-05-26T22:33:41.250863+00:00
[2024-05-26 22:36:42,327] {standard_task_runner.py:52} INFO - Started process 289 to run task
[2024-05-26 22:36:42,332] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_new_data', 'save_into_db', '2024-05-26T22:33:41.250863+00:00', '--job-id', '460', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_new_data.py', '--cfg-path', '/tmp/tmp8rant65r', '--error-file', '/tmp/tmpdajfym2q']
[2024-05-26 22:36:42,335] {standard_task_runner.py:77} INFO - Job 460: Subtask save_into_db
[2024-05-26 22:36:42,360] {logging_mixin.py:104} INFO - Running <TaskInstance: get_new_data.save_into_db 2024-05-26T22:33:41.250863+00:00 [running]> on host 1f334d963743
[2024-05-26 22:36:42,384] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_new_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T22:33:41.250863+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-26T22:33:41.250863+00:00
[2024-05-26 22:36:42,442] {python.py:118} INFO - Done. Returned value was: None
[2024-05-26 22:36:42,448] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=get_new_data, task_id=save_into_db, execution_date=20240526T223341, start_date=20240526T223642, end_date=20240526T223642
[2024-05-26 22:36:42,468] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26 22:36:42,474] {local_task_job.py:146} INFO - Task exited with return code 0
