[2024-05-26 21:41:31,649] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.save_into_db 2024-05-26T21:39:01.326160+00:00 [queued]>
[2024-05-26 21:41:31,659] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.save_into_db 2024-05-26T21:39:01.326160+00:00 [queued]>
[2024-05-26 21:41:31,659] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:41:31,659] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-26 21:41:31,660] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:41:31,665] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-05-26T21:39:01.326160+00:00
[2024-05-26 21:41:31,668] {standard_task_runner.py:52} INFO - Started process 241 to run task
[2024-05-26 21:41:31,671] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_new_data', 'save_into_db', '2024-05-26T21:39:01.326160+00:00', '--job-id', '419', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_new_data.py', '--cfg-path', '/tmp/tmpaon6cfwt', '--error-file', '/tmp/tmp14a9glty']
[2024-05-26 21:41:31,673] {standard_task_runner.py:77} INFO - Job 419: Subtask save_into_db
[2024-05-26 21:41:31,698] {logging_mixin.py:104} INFO - Running <TaskInstance: get_new_data.save_into_db 2024-05-26T21:39:01.326160+00:00 [running]> on host 9c777ac19e23
[2024-05-26 21:41:31,724] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_new_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T21:39:01.326160+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-26T21:39:01.326160+00:00
[2024-05-26 21:41:31,772] {python.py:118} INFO - Done. Returned value was: None
[2024-05-26 21:41:31,779] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=get_new_data, task_id=save_into_db, execution_date=20240526T213901, start_date=20240526T214131, end_date=20240526T214131
[2024-05-26 21:41:31,801] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26 21:41:31,811] {local_task_job.py:146} INFO - Task exited with return code 0
