[2024-05-26 21:30:35,757] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-26T21:30:32.278597+00:00 [queued]>
[2024-05-26 21:30:35,768] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-26T21:30:32.278597+00:00 [queued]>
[2024-05-26 21:30:35,769] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:30:35,769] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-26 21:30:35,770] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:30:35,782] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-05-26T21:30:32.278597+00:00
[2024-05-26 21:30:35,787] {standard_task_runner.py:52} INFO - Started process 174 to run task
[2024-05-26 21:30:35,791] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'save_into_db', '2024-05-26T21:30:32.278597+00:00', '--job-id', '408', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmp4rx33a6_', '--error-file', '/tmp/tmp2gteo30_']
[2024-05-26 21:30:35,794] {standard_task_runner.py:77} INFO - Job 408: Subtask save_into_db
[2024-05-26 21:30:35,828] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.save_into_db 2024-05-26T21:30:32.278597+00:00 [running]> on host 9c777ac19e23
[2024-05-26 21:30:35,873] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T21:30:32.278597+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-26T21:30:32.278597+00:00
[2024-05-26 21:30:36,172] {python.py:118} INFO - Done. Returned value was: None
[2024-05-26 21:30:36,184] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=save_into_db, execution_date=20240526T213032, start_date=20240526T213035, end_date=20240526T213036
[2024-05-26 21:30:36,228] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26 21:30:36,266] {local_task_job.py:146} INFO - Task exited with return code 0
